name: genstatus

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: build-status

      - name: set up git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git pull
          git status
          git checkout build-status
          git log --all --decorate
          git merge origin/master --allow-unrelated-histories

      - name: Install scala and run ./genstatus.scala
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "/home/runner/.sdkman/bin/sdkman-init.sh"
          sdk install scala
          whereis scala
          scala -version
          echo "\n\n=================================="
          scala ./genstatus.scala

      - name: push status
        run: |
          git add status.svg
          git commit -m "update status.svg" || echo "status.svg did not change"
          git push || echo "nothing to push"

